# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.1
    hooks:
      - id: clang-format
        args: [--style=file]
        files: 'client/.*\.(cpp|h|hpp|cc)$'
        exclude: '^.*external/.*$'
      # - id: clang-tidy
      #   args: [--checks='boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*']
