
################################################################################

Main:

    options:

        job:
            kind: string
            default: akmc
            values:
                - parallel_replica
                - saddle_search
                - minimization
                - displacement_sampling
                - process_search
                - basin_hopping
                - akmc
                - hessian
                - md

        potential:
            kind: string
            default: lj
            values:
                - qsc
                - lenosky_Si
                - sw_si
                - lj
                - edip
                - morse_pt
                - zpice
                - bopfox
                - emt
                - eam_al
                - vasp
                - tersoff_si
                - tip4p
                - lammps
                - mpi

        random_seed:
            kind: int
            default: -1

        temperature:
            kind: float
            default: 300.0

        checkpoint:
            kind: boolean
            default: false

        quiet:
            kind: boolean
            default: False

################################################################################

Paths:

    options:

        superbasin_recycling:
            kind: string
            default: "%(main_directory)s/SB_recycling"

        superbasins:
            kind: string
            default: "%(main_directory)s/superbasins/"

        main_directory:
            kind: string
            default: ./

        scratch:
            kind: string
            default: "%(main_directory)s/jobs/scratch/"

        results:
            kind: string
            default: "%(main_directory)s"

        kdb:
            kind: string
            default: "%(main_directory)s/kdb/"

        kdb_scratch:
            kind: string
            default: "%(main_directory)s/kdbscratch/"

        states:
            kind: string
            default: "%(main_directory)s/states/"

        potential_files:
            kind: string
            default: "%(main_directory)s/potfiles"

        jobs_in:
            kind: string
            default: "%(main_directory)s/jobs/in/"

        jobs_out:
            kind: string
            default: "%(main_directory)s/jobs/out/"

        incomplete:
            kind: string
            default: "%(main_directory)s/jobs/incomplete/"

        bh_minima:
            kind: string
            default: "%(main_directory)s/minima"

################################################################################

NEB:

    options:

        images:
            kind: int
            default: 5

        spring:
            kind: boolean
            default: True

        climbing_image_method:
            kind: boolean
            default: False

        old_tangent:
            kind: boolean
            default: False

        opt_method:
            kind: string
            default: OPT_CG

################################################################################

Distributed Replica:

    options:

        sampling steps:
            kind: int
            default: 500

        target_temperature:
            kind: float
            default: 300.0

        balance_steps:
            kind: int
            default: 500

################################################################################

Debug:

    options:

        save_stdout:
            kind: boolean
            default: False

        result_files_path:
            kind: string
            default: ./debug_results/

        interactive_shell:
            kind: boolean
            default: True

        use_mean_time:
            kind: boolean
            default: False

        register_extra_results:
            kind: boolean
            default: False

        target_trajectory:
            kind: boolean
            default: False

        keep_bad_saddles:
            kind: boolean
            default: False

        keep_all_result_files:
            kind: boolean
            default: False

        write_movies:
            kind: boolean
            default: False

################################################################################

Structure Comparison:

    options:

        use_covalent:
            kind: boolean
            default: False

        energy_difference:
            kind: float
            default: 0.01

        brute_neighbors:
            kind: boolean
            default: False

        check_rotation:
            kind: boolean
            default: False

        neighbor_cutoff:
            kind: float
            default: 3.3

        indistinguishable_atoms:
            kind: boolean
            default: True

        distance_difference:
            kind: float
            default: 0.05

        covalent_scale:
            kind: float
            default: 1.3

################################################################################

Dynamics:

    options:

        post_transition_steps:
            kind: int
            default: 500

        andersen_alpha:
            kind: float
            default: 0.2

        langevin_friction:
            kind: float
            default: 0.005

        thermostat:
            kind: string
            default: andersen

        dephase_steps:
            kind: int
            default: 200

        time_step:
            kind: float
            default: 1.0

        check_period:
            kind: int
            default: 500

        bisection_accuracy:
            kind: int
            default: 1

        dephase_loop_max:
            kind: int
            default: 5

        nose_mass:
            kind: float
            default: 1.0

        dephase_loop_stop:
            kind: boolean
            default: False

        steps:
            kind: int
            default: 1000

        andersen_collision_steps:
            kind: float
            default: 10

        auto_stop:
            kind: boolean
            default: True

        refine_transition_time:
            kind: boolean
            default: True

        record_resolution:
            kind: int
            default: 1

################################################################################

Dimer:

    options:

        improved:
            kind: boolean
            default: True

        separation:
            kind: float
            default: 0.001

        torque_min:
            kind: float
            default: 0.1

        opt_method:
            kind: string
            default: sd
            values:
                - sd
                - cg
                - lbfgs

        torque_max:
            kind: float
            default: 1.0

        finite_angle:
            kind: float
            default: 0.005

        rotations_max:
            kind: int
            default: 2

        rotations_min:
            kind: int
            default: 1

        converged_angle:
            kind: float
            default: 1.0

################################################################################

Basin Hopping:

    options:

        max_displacement:
            kind: float
            default: 0.5

        quenching_steps:
            kind: int
            default: 0

        swap_probability:
            kind: float
            default: 0.0

        single_atom_displace:
            kind: boolean
            default: False

        md_first:
            kind: boolean
            default: False

        steps:
            kind: int
            default: 10000

        jump_max:
            kind: int
            default: 0

        significant_structure:
            kind: boolean
            default: False

        displacement_distribution:
            kind: string
            default: uniform
            values:
                - gaussian
                - uniform

        max_displacement_algorithm:
            kind: string
            default: standard
            values:
                - quadratic
                - linear
                - standard

        jump_steps:
            kind: int
            default: 0

        md_probability:
            kind: float
            default: 0.9

        md_temp:
            kind: float
            default: 300.0

################################################################################

Recycling:

    options:

        save_suggestions:
            kind: boolean
            default: False

        move_distance:
            kind: float
            default: 0.2

        use_recycling:
            kind: boolean
            default: False

        use_sb_recycling:
            kind: boolean
            default: False

        displace_moved_only:
            kind: boolean
            default: False

################################################################################

KDB:

    options:

        use_kdb:
            kind: boolean
            default: False

        insertpath:
            kind: string
            default: kdbinsert.py

        querypath:
            kind: string
            default: kdbquery.py

        wait:
            kind: boolean
            default: False

        keep:
            kind: boolean
            default: False

        Kdb_only:
            kind: boolean
            default: False

################################################################################

Hyperdynamics:

    options:

        bb_dvmax:
            kind: float
            default: 0.0

        bias_potential:
            kind: string
            default: none
            values:
                - bond_boost
                - none

        bb_rmd_steps:
            kind: int
            default: 0

        bb_rcut:
            kind: float
            default: 3.0

        bb_strech_threshold:
            kind: float
            default: 0.0001

        bb_ds_curvature:
            kind: float
            default: 3.95

################################################################################

Process Search:

    options:

        prefactor_max:
            kind: float
            default: 1e+21

        default_prefactor:
            kind: float
            default: 0

        minimization_offset:
            kind: float
            default: 0.2

        minimize_first:
            kind: boolean
            default: False

        prefactor_min:
            kind: float
            default: 1000000000.0

################################################################################

Hessian:

    options:

        finite_dist:
            kind: float
            default: 0.001

        type:
            kind: string
            default: reactant

        min_displacement:
            kind: float
            default: 0.25

        within_radius:
            kind: float
            default: 5.0

################################################################################

Lanczos:

    options:

        finite_dist:
            kind: float
            default: 0.001

        tolerance:
            kind: float
            default: 0.001

        max_iterations:
            kind: int
            default: 20

################################################################################

AKMC:

    options:

        confidence:
            kind: float
            default: 0.99

        server_side:
            kind: boolean
            default: false

        max_kmc_steps:
            kind: int
            default: 100000

        confidence_scheme:
            kind: string
            default: new
            values:
                - new
                - old

        thermally_accessible_window:
            kind: float
            default: 20

        thermally_accessible_buffer:
            kind: float
            default: 0

        confidence_correction:
            kind: boolean
            default: False

################################################################################

Communicator:

    options:

        boinc_project_dir:
            kind: string
            default: ./

        boinc_priority:
            kind: int
            default: 1

        client_path:
            kind: string
            default: eonclient

        number_of_CPUs:
            kind: int
            default: 1

        blacklist:
            kind: string
            default: None

        queued_jobs:
            kind: string
            default: queued_jobs.sh

        boinc_re_template_path:
            kind: string
            default: None

        boinc_results_path:
            kind: string
            default: "%(boinc_project_dir)s/sample_results"

        boinc_wu_template_path:
            kind: string
            default: None

        jobs_per_bundle:
            kind: int
            default: 1

        cancel_job:
            kind: string
            default: cancel_job.sh

        boinc_appname:
            kind: string
            default: eonclient

        script_path:
            kind: string
            default: ./

        name_prefix:
            kind: string
            default: eon

        type:
            kind: string
            default: local
            values:
                - cluster
                - arc
                - local
                - boinc
                - mpi

        submit_job:
            kind: string
            default: submit_job.sh

        num_jobs:
            kind: int
            default: 1

################################################################################

Saddle Search:

    options:

        disp_at_random:
            kind: int
            default: 1

        displace_atomlist:
            kind: string
            default: 0

        max_step_size:
            kind: float
            default: 0.2

        displace_radius:
            kind: float
            default: 5.0

        max_single_displace:
            kind: float
            default: 10.0

        max_localized_atoms:
            kind: int
            default: 0

        stdev_rotation:
            kind: float
            default: 1.0

        client_max_single_displace:
            kind: int
            default: 10

        displace_max_coordination:
            kind: int
            default: 11

        push_displacement:
            kind: boolean
            default: False

        max_iterations:
            kind: int
            default: 1000

        min_mode_method:
            kind: string
            default: dimer
            values:
                - dimer
                - lanczos

        nonzero_mode:
            kind: float
            default: 0.01

        concave_step:
            kind: float
            default: 0.1
            
        displace_frac_random:
            kind: float
            default: 0.0
        
        displace_frac_listed:
            kind: float
            default: 0.0

        displace_frac_not_FCC_HCP:
            kind: float
            default: 0.0

        displace_frac_under_coordinated:
            kind: float
            default: 0.0
        
        displace_frac_least_coordinated:
            kind: float
            default: 0.0
        
        displace_frac_water:
            kind: float
            default: 0.0

        client_displace_type:
            kind: string
            default: load
            values:
                - least_coordinated
                - last_atom
                - load
                - not_FCC_HCP_coordinated

        perp_force_ratio:
            kind: float
            default: 0.0

        displace_min_norm:
            kind: float
            default: 0.0

        molecule_list:
            kind: string
            default: []

        displace_magnitude:
            kind: float
            default: 0.1

        stdev_translation:
            kind: float
            default: 0.2

        max_energy:
            kind: float
            default: 20.0

        converged_force:
            kind: float
            default: 0.01

################################################################################

Coarse Graining:

    options:

        number_of_transitions:
            kind: int
            default: 5

        askmc_high_barrier_def:
            kind: int
            default: 2

        use_askmc:
            kind: boolean
            default: False

        superbasin_scheme:
            kind: string
            default: transition_counting

        use_projective_dynamics:
            kind: boolean
            default: False

        state_file:
            kind: string
            default: superbasin

        askmc_barrier_raise_param:
            kind: float
            default: 1.5

        energy_increment:
            kind: float
            default: 0.01

        askmc_barrier_test_on:
            kind: boolean
            default: True

        askmc_connections_test_on:
            kind: boolean
            default: False

        askmc_confidence:
            kind: float
            default: 0.9

################################################################################

Optimizers:

    options:

        converged_force:
            kind: float
            default: 0.01

        finite_dist:
            kind: float
            default: 0.001

        max_move:
            kind: float
            default: 0.2

        time_step:
            kind: float
            default: 0.1

        max_iterations:
            kind: int
            default: 1000

        opt_method:
            kind: string
            default: cg
            values:
                - box
                - cg
                - qm
