# To use:
#
#   $ micromamba env create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate gprd
#
name: eongit
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - gfortran
  - pkg-config
  # Pinned
  - eigen==3.3.9
  # AMS
  - boost-cpp
  - fmt
  - abseil-cpp
