# To use:
#
#   $ micromamba create -n eongit -f conda-lock.yml # conda works for this as well
#   $ micromamba activate eongit
#
name: eongit
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - cython # For qsc
  - ninja
  - gfortran
  - pkg-config
  - openblas
  # Pinned
  - "eigen==3.4.0"
  - "fmt<=10"
  - "spdlog<=1.14"
  # AMS
  - boost-cpp
  - abseil-cpp
  # Docs
  - towncrier
  - pipx # conda-lock pdm
  # Lint
  - cppcheck
  - cpplint
  - ruff
