# To use:
#
#   $ micromamba env create -f environment.yml  # `conda` works too for this command
#   $ micromamba activate eongit
#
name: eongit
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - cython # For qsc
  - ninja
  - gfortran
  - pkg-config
  - openblas
  # Pinned
  - eigen==3.4.0
  # AMS
  - boost-cpp
  - fmt
  - spdlog
  - abseil-cpp
  # Testing
  - pytest
  - pytest-datadir
  # Extras
  - numpy
  - ase
  - PyYAML
  - pytest
  - pytest-datadir
  - sh
  # Docs
  - towncrier
  - pipx
  # Lint
  - cppcheck
  - cpplint
