name: Build basic eon
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "eon_basic"
  cancel-in-progress: false
on: [push, pull_request]
jobs:
  build_eon:
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, macos-14, macos-12, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Compile and install
        shell: bash -el {0}
        run: |
          meson setup bbdir --prefix $CONDA_PREFIX --libdir=lib
          meson install -C bbdir
      - name: Run tests
        run: |
          cd examples/akmc-al
          python -m eon.server
