name: Build documentation
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Generate Docs
        shell: bash -el {0}
        run: |
          micromamba install pipx
          pipx run pdm sync
          pipx run pdm run pip install . -vvv
          pipx run pdm run sphinx-build -b html docs/source html
      - name: Archive artifact
        shell: sh
        run: |
          tar \
          --dereference --hard-dereference \
          --exclude=.git \
          --exclude=.github \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --directory=html .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build_docs
    if: github.event_name == 'push' && github.repository == 'atomic-solvers/featom'
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
